{{- if .Values.checkoutService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.checkoutService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.checkoutService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.checkoutService.name }}
    spec:
      imagePullSecrets: 
  {{- toYaml .Values.imagePullSecrets.name | nindent 8 }}
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.checkoutService.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      {{- if .Values.securityContext.enable }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        {{- if .Values.seccompProfile.enable }}
        seccompProfile:
          type: {{ .Values.seccompProfile.type }}
        {{- end }}
      {{- end }}
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.checkoutService.image.repository }}:{{ .Values.checkoutService.image.tag | default .Chart.AppVersion }}

        ports:
        - containerPort: 5050
        readinessProbe:
          grpc:
            port: 5050
        livenessProbe:
          grpc:
            port: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "{{ .Values.productCatalogService.name }}:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "{{ .Values.shippingService.name }}:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "{{ .Values.paymentService.name }}:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "{{ .Values.emailService.name }}:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "{{ .Values.currencyService.name }}:7000"
        - name: CART_SERVICE_ADDR
          value: "{{ .Values.cartService.name }}:7070"
        {{- if .Values.opentelemetryCollector.create }}
        - name: COLLECTOR_SERVICE_ADDR
          value: "{{ .Values.opentelemetryCollector.name }}:4317"
        - name: OTEL_SERVICE_NAME
          value: "{{ .Values.checkoutService.name }}"
        {{- end }}
        resources:
          {{- toYaml .Values.checkoutService.resources | nindent 10 }}
{{- end }}
