{{- if .Values.frontend.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      imagePullSecrets: 
  {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.frontend.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      {{- if .Values.securityContext.enable }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        {{- if .Values.seccompProfile.enable }}
        seccompProfile:
          type: {{ .Values.seccompProfile.type }}
        {{- end }}
      {{- end }}
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-liveness-probe"
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "{{ .Values.productCatalogService.name }}:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "{{ .Values.currencyService.name }}:7000"
        - name: CART_SERVICE_ADDR
          value: "{{ .Values.cartService.name }}:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "{{ .Values.recommendationService.name }}:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "{{ .Values.shippingService.name }}:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "{{ .Values.checkoutService.name }}:5050"
        - name: AD_SERVICE_ADDR
          value: "{{ .Values.adService.name }}:9555"
        - name: SHOPPING_ASSISTANT_SERVICE_ADDR
          value: "{{ .Values.shoppingAssistantService.name }}:80"
        - name: ENV_PLATFORM
          value: {{ .Values.frontend.platform | quote }}
        {{- if .Values.opentelemetryCollector.create }}
        - name: COLLECTOR_SERVICE_ADDR
          value: "{{ .Values.opentelemetryCollector.name }}:4317"
        - name: OTEL_SERVICE_NAME
          value: "{{ .Values.frontend.name }}"
        {{- end }}
        - name: CYMBAL_BRANDING
          value: {{ .Values.frontend.cymbalBranding | quote }}
        - name: ENABLE_ASSISTANT
          value: {{ .Values.shoppingAssistantService.create | quote }}
        - name: ENABLE_SINGLE_SHARED_SESSION
          value: {{ .Values.frontend.singleSharedSession | quote }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
