{{- if .Values.productCatalogService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.productCatalogService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.productCatalogService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.productCatalogService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.productCatalogService.name }}
    spec:
      imagePullSecrets: 
  {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.productCatalogService.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      terminationGracePeriodSeconds: 5
      {{- if .Values.securityContext.enable }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        {{- if .Values.seccompProfile.enable }}
        seccompProfile:
          type: {{ .Values.seccompProfile.type }}
        {{- end }}
      {{- end }}
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.productCatalogService.image.repository }}:{{ .Values.productCatalogService.image.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        {{- if .Values.opentelemetryCollector.create }}
        - name: COLLECTOR_SERVICE_ADDR
          value: "{{ .Values.opentelemetryCollector.name }}:4317"
        - name: OTEL_SERVICE_NAME
          value: "{{ .Values.productCatalogService.name }}"
        {{- end }}
        - name: DISABLE_PROFILER
          value: "1"
        - name: EXTRA_LATENCY
          value: {{ .Values.productCatalogService.extraLatency }}
        readinessProbe:
          grpc:
            port: 3550
        livenessProbe:
          grpc:
            port: 3550
        resources:
          {{- toYaml .Values.productCatalogService.resources | nindent 10 }}
{{- end }}
