{{- if .Values.shippingService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.shippingService.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.shippingService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.shippingService.name }}
    spec:
      imagePullSecrets: 
 {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.shippingService.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      {{- if .Values.securityContext.enable }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        {{- if .Values.seccompProfile.enable }}
        seccompProfile:
          type: {{ .Values.seccompProfile.type }}
        {{- end }}
      {{- end }}
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{.Values.shippingService.image.repository}}:{{.Values.shippingService.image.tag}}
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 50051
        livenessProbe:
          grpc:
            port: 50051
        resources:
          {{- toYaml .Values.shippingService.resources | nindent 10 }}
{{- end }}
