---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: tcp
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: clickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
