{{- if .Values.emailService.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.emailService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.emailService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.emailService.name }}
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080
{{- end }}
