{{- if and .Values.frontend.create .Values.frontend.externalService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-external
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "building-and-testing-workloads"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
{{- end }}
