name: Build and Push Docker Images

on:
  workflow_dispatch: {}
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: adservice
            dockerfile: services/adservice/Dockerfile
          - name: checkoutservice
            dockerfile: services/checkoutservice/Dockerfile
          - name: currencyservice
            dockerfile: services/currencyservice/Dockerfile
          - name: emailservice
            dockerfile: services/emailservice/Dockerfile
          - name: frontend
            dockerfile: services/frontend/Dockerfile
          - name: loadgenerator
            dockerfile: services/loadgenerator/Dockerfile
          - name: paymentservice
            dockerfile: services/paymentservice/Dockerfile
          - name: productcatalogservice
            dockerfile: services/productcatalogservice/Dockerfile
          - name: recommendationservice
            dockerfile: services/recommendationservice/Dockerfile
          - name: shippingservice
            dockerfile: services/shippingservice/Dockerfile
          - name: shoppingassistantservice
            dockerfile: services/shoppingassistantservice/Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.service.name }}
        run: |
          image_name="ghcr.io/${{ github.repository_owner }}/svc_${{ matrix.service.name }}"
          echo "Building image: $image_name using Dockerfile ${{ matrix.service.dockerfile }}"
          docker build -t "$image_name" -f "${{ matrix.service.dockerfile }}" "$(dirname "${{ matrix.service.dockerfile }}")"
          docker push "$image_name"
