name: Deploy to Kubernetes cluster on Azure

on:
  workflow_dispatch: {}
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - count: 1
            name: adservice
          - count: 2
            name: checkoutservice
          - count: 3
            name: currencyservice
          - count: 4
            name: emailservice
          - count: 5
            name: frontend
          - count: 6
            name: loadgenerator
          - count: 7
            name: paymentservice
          - count: 8
            name: productcatalogservice
          - count: 9
            name: recommendationservice
          - count: 10
            name: shippingservice
          - count: 11
            name: shoppingassistantservice
          - count: 12
            name: cartservice

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: building-and-testing-workloads
          cluster-name: ag-cluster-1
          admin: 'false'
          use-kubelogin: 'true'

      - name: Verify AKS Connection
        run: |
          kubectl get nodes

      # Package the Helm chart from the helm/ directory into xnl-innovations-hiring-challenge-0.1.0.tgz
      - name: Package Helm Chart
        run: |
          cd helm
          helm package . --version 0.1.0 --app-version 0.1.0 --destination ..
          mv ../helm-0.1.0.tgz ../xnl-innovations-hiring-challenge-0.1.0.tgz || true
          ls -l ..

      - name: Deploy ${{ matrix.service.name }} via Helm
        run: |
          IMAGE="ghcr.io/abhijithganesh/svc_${{ matrix.service.count }}_${{ matrix.service.name }}"
          echo "Deploying ${{ matrix.service.name }} using image: $IMAGE"

          # Use the packaged chart xnl-innovations-hiring-challenge-0.1.0.tgz
          # and also supply a local values.yaml file for overrides
          helm upgrade --install ${{ matrix.service.name }} xnl-innovations-hiring-challenge-0.1.0.tgz \
            -f helm/values.yaml \
            --set image.repository=$IMAGE \
            --set image.tag=latest \
            --namespace default \
            --create-namespace
