name: Deploy to Kubernetes cluster on Azure

on:
  workflow_dispatch: {}
  workflow_run:
    branches:
      - prod
    workflows: ["Build and Push Docker Images to GitHub Container Registry"]
    types:
      - completed
jobs:
  deploy-to-aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write Kubeconfig from Secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.AZURE_CREDENTIALS }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify AKS Connection
        run: kubectl get nodes

      - name: Run additional build scripts
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo "Deploying Istio..."
          ./scripts/istio.sh
          echo "Deploying Cilium..."
          ./cillium/cillium.sh

      - name: Create GHCR Secret in Kubernetes
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=abhijithganesh \
            --docker-password="${{ secrets.GHCR_TOKEN }}" \
            --namespace default || echo "GHCR secret already exists"

      - name: Package Helm Chart
        run: |
          cd helm
          helm package . --version 0.1.0 --app-version 0.1.0 --destination ..
          mv ../helm-0.1.0.tgz ../xnl-innovations-hiring-challenge-0.1.0.tgz || true
          ls -l ..

      - name: Deploy via Helm
        run: |
          IMAGE="ghcr.io/abhijithganesh/svc_1_adservice"
          echo "Deploying service using image: $IMAGE"
          helm upgrade --install adservice xnl-innovations-hiring-challenge-0.1.0.tgz \
            -f helm/values.yaml \
            --set image.repository=$IMAGE \
            --set image.tag=latest \
            --namespace default \
            --create-namespace
