name: Build and Push Docker Images to GitHub Container Registry

on:
  workflow_dispatch: {}
  workflow_run:
    branches:
      - prod
    workflows: ["Helm Lint"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push ${{ matrix.service.name }}
    strategy:
      matrix:
        service:
          - count: 1
            name: adservice
            dockerfile: services/adservice/Dockerfile
          - count: 2
            name: checkoutservice
            dockerfile: services/checkoutservice/Dockerfile
          - count: 3
            name: currencyservice
            dockerfile: services/currencyservice/Dockerfile
          - count: 4
            name: emailservice
            dockerfile: services/emailservice/Dockerfile
          - count: 5
            name: frontend
            dockerfile: services/frontend/Dockerfile
          - count: 6
            name: loadgenerator
            dockerfile: services/loadgenerator/Dockerfile
          - count: 7
            name: paymentservice
            dockerfile: services/paymentservice/Dockerfile
          - count: 8
            name: productcatalogservice
            dockerfile: services/productcatalogservice/Dockerfile
          - count: 9
            name: recommendationservice
            dockerfile: services/recommendationservice/Dockerfile
          - count: 10
            name: shippingservice
            dockerfile: services/shippingservice/Dockerfile
          - count: 11
            name: shoppingassistantservice
            dockerfile: services/shoppingassistantservice/Dockerfile
          - count: 12
            name: cartservice
            dockerfile: services/zcartservice/src/Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push ${{ matrix.service.name }} Docker Image
        run: |
          image_name="ghcr.io/abhijithganesh/svc_${{ matrix.service.count }}_${{ matrix.service.name }}"
          echo "Building image ${{ matrix.service.count }}: $image_name using Dockerfile ${{ matrix.service.dockerfile }}"
          docker build -t "$image_name" -f "${{ matrix.service.dockerfile }}" "$(dirname "${{ matrix.service.dockerfile }}")"
          docker push "$image_name"
