name: Deploy to Kubernetes cluster on Azure

on:
  workflow_dispatch: {}
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - count: 1
            name: adservice
          - count: 2
            name: checkoutservice
          - count: 3
            name: currencyservice
          - count: 4
            name: emailservice
          - count: 5
            name: frontend
          - count: 6
            name: loadgenerator
          - count: 7
            name: paymentservice
          - count: 8
            name: productcatalogservice
          - count: 9
            name: recommendationservice
          - count: 10
            name: shippingservice
          - count: 11
            name: shoppingassistantservice
          - count: 12
            name: cartservice

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: building-and-testing-workloads
          cluster-name: ag-cluster-1
          admin: 'false'
          use-kubelogin: 'true'

      - name: Verify AKS Connection
        run: |
          kubectl get nodes

      - name: Run additional build scripts
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          # Check and run Istio deployment script if it exists.
          if [ -f ./scripts/istio.sh ]; then
            run_and_time "Deploying Istio..." ./scripts/istio.sh
          else
            echo "Istio script not found or Istio already installed, skipping."
          fi

          # Check and run Cilium deployment script if it exists.
          if [ -f ./cillium/cillium.sh ]; then
            run_and_time "Deploying Cilium..." ./cillium/cillium.sh
          else
            echo "Cilium script not found or Cilium already installed, skipping."
          fi

      - name: Create GHCR Secret in Kubernetes
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=abhijithganesh \
            --docker-password="${{ secrets.GHCR_TOKEN }}" \
            --namespace default || echo "GHCR secret already exists"

      - name: Package Helm Chart
        run: |
          cd helm
          helm package . --version 0.1.0 --app-version 0.1.0 --destination ..
          mv ../helm-0.1.0.tgz ../xnl-innovations-hiring-challenge-0.1.0.tgz || true
          ls -l ..

      - name: Deploy ${{ matrix.service.name }} via Helm
        run: |
          IMAGE="ghcr.io/abhijithganesh/svc_${{ matrix.service.count }}_${{ matrix.service.name }}"
          echo "Deploying ${{ matrix.service.name }} using image: $IMAGE"
          helm upgrade --install ${{ matrix.service.name }} xnl-innovations-hiring-challenge-0.1.0.tgz \
            -f helm/values.yaml \
            --set image.repository=$IMAGE \
            --set image.tag=latest \
            --namespace default \
            --create-namespace
